[general]
import = ["./os.toml", "./themes/terafox.toml"]

[window]
opacity = 0.8
blur = false
#dimensions = { columns = 240, lines = 60 }
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
size = 10.0
builtin_box_drawing = true
normal = { family = "Moralerspace Krypton HWNF", style = "Regular" }

[terminal]
osc52 = "CopyPaste"

[selection]
save_to_clipboard = true

[mouse]
bindings = [
  { mouse = "Right", action = "Paste" },
]
