[window]
opacity = 0.8

[font]
size = 8.0

[font.normal]
family = "Moralerspace Krypton HWNF"
style = "Regular"

[font.offset]
y = 2

[cursor]
style = { shape = "Hollow" }

[colors.primary]
background = "#152528"
foreground = "#E6EAEA"

[colors.cursor]
text = "CellBackground"
cursor = "#E6EAEA"

[colors.selection]
text = "CellForeground"
background = "#293E40"

[colors.normal]
black = "#2F3239"
red = "#E85C51"
green = "#7AA4A1"
yellow = "#FDA47F"
blue = "#5A93AA"
magenta = "#AD5C7C"
cyan = "#A1CDD8"
white = "#EBEBEB"

[colors.bright]
black = "#4E5157"
red = "#EB746B"
green = "#8EB2AF"
yellow = "#FDB292"
blue = "#73A3B7"
magenta = "#B97490"
cyan = "#AFD4DE"
white = "#EEEEEE"
