[tools]
node = "latest"
npm = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:wsl-open" = "latest"

[tasks.chrome-remote-debug]
run = """
pwsh.exe -Command "& 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' --remote-debugging-port=9222 --user-data-dir='C:\\temp\\chrome-remote-debug'"
"""
